// <auto-generated />
using System;
using LancaProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LancaProj.Migrations
{
    [DbContext(typeof(LancaProjContext))]
    partial class LancaProjContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LancaProj.Pages.Models.Adm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Dia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Adm");
                });

            modelBuilder.Entity("LancaProj.Pages.Models.Horario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AdmID")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("FunEntrada")
                        .HasColumnType("interval");

                    b.Property<bool>("FunFolga")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("FunPausa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("FunSaida")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("FunVolta")
                        .HasColumnType("interval");

                    b.HasKey("ID");

                    b.HasIndex("AdmID");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("LancaProj.Pages.Models.Horario", b =>
                {
                    b.HasOne("LancaProj.Pages.Models.Adm", "Adm")
                        .WithMany("HorariosRegistrados")
                        .HasForeignKey("AdmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adm");
                });

            modelBuilder.Entity("LancaProj.Pages.Models.Adm", b =>
                {
                    b.Navigation("HorariosRegistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
